sudo: required
services:
	- docker
	
before_install:
	- docker build -t jimakos/docker-react-test -f Dockerfile.dev .
    
script:
    - docker run jimakos/docker-react-test npm run test -- --coverage